### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by Tjoosten** [Tjoosten/HTML-tags-referentie#1]
### Shiplist 1.0.1
- [x] [#2](https://github.com/Tjoosten/HTML-tags-referentie/commit/95f9308395ade1f9e3a2be3f8fdb2c3147428820): Verwijderen `bold formatting` bij tags.
- [x] [#3](https://github.com/Tjoosten/HTML-tags-referentie/commit/5463f8ad243ad51ec751b64e0fd6877a5d9a776c): Toevoegen van een contributie file.
- [x] [#4](https://github.com/Tjoosten/HTML-tags-referentie/commit/79db360a27d60bea1eabb7a473dcd198c646b5f9): Toevoegen van een licentie.
- [ ] Tags (html) een pagina geven waar mee informatie opstaat
- [x] [#6](https://github.com/Tjoosten/HTML-tags-referentie/commit/b1dfd32d5aebcdc13dbbe4d5556e6598b5045c9e) Coding template
- [x] [#7](https://github.com/Tjoosten/HTML-tags-referentie/commit/5fb5a2c17338f627b51fce274e5a669466b3f6b7): Basis tags in tabel
